# Generated by Django 5.1.7 on 2025-03-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role_and_user_connex',
            old_name='user',
            new_name='userID',
        ),
    ]
