# Generated by Django 5.1.7 on 2025-03-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_enquete_enqueteresponse_questions_responseselection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseselection',
            name='note',
            field=models.IntegerField(),
        ),
    ]
