# Generated by Django 5.1.7 on 2025-03-29 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_responseselection_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquete',
            name='start_date',
            field=models.DateField(),
        ),
    ]
