# Generated by Django 5.1.7 on 2025-03-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_enquete_creation_date_alter_enquete_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquete',
            name='roleID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='home.role_and_user_connex'),
            preserve_default=False,
        ),
    ]
