# Generated by Django 5.1.7 on 2025-03-29 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_enquete_roleid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='roleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='home.role'),
        ),
        migrations.AlterField(
            model_name='role_and_user_connex',
            name='roleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_connex', to='home.role'),
        ),
        migrations.AlterField(
            model_name='role_and_user_connex',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_connex', to=settings.AUTH_USER_MODEL),
        ),
    ]
