# Generated by Django 5.1.7 on 2025-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_enquete_roleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquete',
            name='roleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquete', to='home.role_and_user_connex'),
        ),
    ]
