# Generated by Django 5.1.7 on 2025-03-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_enquete_roleid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enqueteresponse',
            old_name='responseDateTime',
            new_name='response',
        ),
    ]
