# Generated by Django 5.1.7 on 2025-04-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_responsedatetime_enqueteresponse_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enqueteresponse',
            old_name='response',
            new_name='responseDate',
        ),
    ]
