# Generated by Django 5.1.6 on 2025-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_response_enqueteresponse_responsedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enqueteresponse',
            name='validationDateTime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
