# Generated by Django 5.1.6 on 2025-04-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_enqueteresponse_validationdatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponses',
            name='enqueteResponseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='home.enqueteresponse'),
        ),
    ]
