# Generated by Django 5.1.6 on 2025-04-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_reponses_responseselectionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponses',
            name='enqueteResponseID',
        ),
        migrations.AddField(
            model_name='reponses',
            name='enqueteResponseID',
            field=models.ManyToManyField(null=True, related_name='reponses', to='home.enqueteresponse'),
        ),
    ]
